### ISSUE TITLE
Adding the possibility to contribute

### ISSUE THREAD

**Issue by Dynnammo** [fossfox-com/fossfox#5]
As an OSS promoter, I'm surprised that there's no CONTRIBUTING.md file or any related section in the README.md

Since the project aims to help companies that recruit high-skilled workers, it could be useful to add the possibility to contribute either technically (furnish hosting, translation, etc.) or financially (through OpenCollective or Github Sponsors as instance)

**Comment by 4kimov** [comment]
Hi @Dynnammo,

[CONTRIBUTING.md](https://github.com/fossfox-com/fossfox/blob/main/CONTRIBUTING.md) file has been added. It's the same as the "How To Post" section in the main README. There's no need for translations in this repo yet as the main website does not support that, and no need for Github Sponsors since paid posts will cover that within the app.

Thank you for the feedback.
